# Generated by Django 4.2.3 on 2023-07-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='vote',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
