# Generated by Django 5.0.7 on 2024-10-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_app', '0004_alter_piano_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='vote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
