# Generated by Django 5.0.7 on 2024-10-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_app', '0007_rename_vote_piano_vote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('piano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piano_app.piano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piano_app.user')),
            ],
        ),
    ]
