# Generated by Django 5.1.7 on 2025-03-23 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_app', '0008_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='piano',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pianos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='piano',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='piano',
        ),
        migrations.AddField(
            model_name='vote',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piano_votes', to='piano_app.piano'),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Upvote'), (-1, 'Downvote')], null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
