# Generated by Django 5.1.7 on 2025-03-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano_app', '0009_alter_piano_owner_remove_vote_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], null=True),
        ),
    ]
